dist: bionic

language: php

php:
  - '7.4'

before_install:
  - travis_retry make travis_before_install

install:
  - travis_retry make travis_install

script:
  - make travis_test_cov

after_success:
  - make travis_codecov